parameters:
    gn36.firstpostedit.forums: [1,2,3]

services:
    gn36.firstpostedit.listener:
        class: gn36\firstpostedit\event\listener
        arguments:
            - %gn36.firstpostedit.forums%
        tags:
            - { name: event.listener }
